repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer

- repo: local
  hooks:
  - id: format
    name: format
    entry: make format
    types: [python]
    language: system
