[tool.poetry]
name = "typing-extend"
version = "0.0.1"
description = "Extend typing package functionalities"
authors = ["Eric Jolibois <em.jolibois@gmail.com>"]
license = "MIT"
repository = "https://github.com/PrettyWood/typing-extend"
homepage = "https://github.com/PrettyWood/typing-extend"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10"
]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
mypy = "^0.790"
pytest = "^6.2.1"
pytest-cov = "^2.10.1"
tox = "^3.21.0"

[tool.black]
line-length = 100
target-version = ["py38"]

[tool.pytest.ini_options]
addopts = "--cov typing_extend --cov-report=term-missing --cov-report=xml"
testpaths = ["tests"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
